### PR TITLE
adding eShop demo

### PR DESCRIPTION
**Pull request by CawaMS**
## Purpose

* ...

## Does this introduce a breaking change?

```
[ ] Yes
[ ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Review by philon-msft — CHANGES_REQUESTED** [review]
Could you also update the README.md in the root of the repo?

**Comment by CawaMS** [comment]
> Could you also update the README.md in the root of the repo?

@philon-msft what content do you want me to put in the README.md in the root of the repo?

**Comment by philon-msft** [comment]
> > Could you also update the README.md in the root of the repo?
> 
> @philon-msft what content do you want me to put in the README.md in the root of the repo?

Whatever is necessary to make it look like this is an official/professional repo owned by our service. We should describe its purpose and link to our public documentation. We should also list the project you're adding and include a link to its location in the repo. I'd format the README so it's easy to add more demo projects in the future. The README in our samples repo may be a helpful example: https://github.com/Azure-Samples/azure-cache-redis-samples/blob/main/README.md

**Comment by CawaMS** [comment]
> > > Could you also update the README.md in the root of the repo?
> > 
> > 
> > @philon-msft what content do you want me to put in the README.md in the root of the repo?
> 
> Whatever is necessary to make it look like this is an official/professional repo owned by our service. We should describe its purpose and link to our public documentation. We should also list the project you're adding and include a link to its location in the repo. I'd format the README so it's easy to add more demo projects in the future. The README in our samples repo may be a helpful example: https://github.com/Azure-Samples/azure-cache-redis-samples/blob/main/README.md

Edited README.md in the root of the repo.

**Review by philon-msft — APPROVED** [review]

**Pull request merged**
