### PR TITLE
Add Playwright tests

### PR DESCRIPTION
**Pull request by MarcusFelling**
Playwright tests have been added to e2e test login, shopping cart performance, product listings, and more.

[README](https://github.com/Azure-Samples/azure-cache-redis-demos/blob/30bd7b5bd84e3152f5bba4ab84067bd923194b41/tests/README.md)

### CODE REVIEW

**Comment by philon-msft** [comment]
@MarcusFelling Is this PR in the right repo? I don't see anything related to Redis in the code

**Comment by MarcusFelling** [comment]
> @MarcusFelling Is this PR in the right repo? I don't see anything related to Redis in the code

@philon-msft - yes, this was requested by @CawaMS. These are UI tests that exercise the web app. I'll also be adding load tests. separate PR coming soon...

**Comment by philon-msft** [comment]
> > @MarcusFelling Is this PR in the right repo? I don't see anything related to Redis in the code
> 
> @philon-msft - yes, this was requested by @CawaMS. These are UI tests that exercise the web app. I'll also be adding load tests. PR coming soon...

Great - thanks for your contribution!

**Comment by CawaMS** [comment]
Are we merging this pull request? @philon-msft @MarcusFelling

**Comment by MarcusFelling** [comment]
> Are we merging this pull request? @philon-msft @MarcusFelling

Good to go on my end. @philon-msft, who do we need to sign off?

**Comment by philon-msft** [comment]
@CawaMS I've added you as a maintainer on the repo. Feel free to merge when you're satisfied with quality

**Pull request merged**
